
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/sync"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/build/docker-buildx"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/build/gitlab-runner-helper"
    schedule:
      interval: "daily"
